### ISSUE TITLE
Image missing? [Create your first substrate chain" tut]

### ISSUE THREAD

**Issue by bjornwgnr** [substrate-developer-hub/tutorials#20]
On the first page of https://staging.substrate.io/tutorials/create-your-first-substrate-chain

<img width="414" alt="Screenshot 2020-04-22 at 17 25 20" src="https://user-images.githubusercontent.com/17831185/80001339-89df8000-84be-11ea-9c8d-a4c94f726b11.png">

**Comment by danforbes** [comment]
This should be fixed in 2.0.0-alpha.6; Joshy and I fixed this when we were going through and updating the tutorials. We changed the path for this image [from `assets/forks.png`](https://raw.githubusercontent.com/substrate-developer-hub/tutorials/master/tuts/create-your-first-substrate-chain/v2.0.0-alpha.5/background.md) to [`../assets/forks.png`](https://github.com/substrate-developer-hub/tutorials/commit/2f77c47eff7cf670c299588b2e5c574db5805b1e#diff-1994f349e46ea8f6fa2ba879da55cac8R33) and built the page to ensure it resolved properly :+1:

**Comment by JoshOrndorff** [comment]
Yes, we fixed in the alpha.6 which is the latest version. But there were two remaining problems.

1. We hadn't fixed it in the old alpha.5. That is fixed in #24 
2. The website still thinks alpha.5 is current. That is reported in #23
