### ISSUE TITLE
Private network, no peer seeing.

### ISSUE THREAD

**Issue by herou** [substrate-developer-hub/tutorials#48]
Hello, 
I am trying to launch my private network using the pre-generated keys. Everything goes well but I do not see any peer appearing :/ The image may help.

Any idea?

![image](https://user-images.githubusercontent.com/13895430/83363959-c2b42400-a39d-11ea-867a-1832c9b415ca.png)

**Comment by danforbes** [comment]
It looks like your nodes were working at one point because in the "top" window I notice that, even though the node isn't finalizing any _more_ blocks, it _had_ finalized almost 1,000 blocks. You may want to try purging your node state with `./target/release/node-template purge-chain --base-path /tmp/alice --chain local` (and then do the same for Bob) and start again from the beginning.

**Comment by herou** [comment]
The issue above is related to this https://www.substrate.io/tutorials/start-a-private-network/v2.0.0-rc2/customchain  part of the tutorial. I have been able to see Bob joining Alice's network.

**Comment by danforbes** [comment]
The command in the top window is for "a Bob node" so you may be mixing commands, then. The "custom chain" part of the tutorial starts from scratch and doesn't involve the Alice and Bob nodes.

**Comment by danforbes** [comment]
@herou - please let us know if you need additional help. Otherwise, please close this issue :pray:
